# Generated by Django 2.2.4 on 2019-08-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='large_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='small_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
