# Generated by Django 2.2.4 on 2019-08-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190821_0612'),
        ('toppings', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoOrden',
            new_name='ProductOrder',
        ),
        migrations.RenameModel(
            old_name='ToppingOrden',
            new_name='ToppingOrder',
        ),
    ]
