# Generated by Django 2.2.4 on 2019-08-22 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_auto_20190822_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
        migrations.AlterField(
            model_name='toppingorder',
            name='topping',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='toppings.Topping'),
        ),
    ]
