# Generated by Django 2.2.4 on 2019-08-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_auto_20190822_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(null=True, to='ordenes.ProductOrder'),
        ),
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(null=True, to='ordenes.ToppingOrder'),
        ),
    ]
