# Generated by Django 2.2.4 on 2019-08-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_auto_20190823_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppingorder',
            name='topping',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(null=True, to='productos.Producto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(null=True, to='toppings.Topping'),
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.DeleteModel(
            name='ToppingOrder',
        ),
    ]
