# Generated by Django 2.2.4 on 2019-08-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_auto_20190823_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
