# Generated by Django 2.2.4 on 2019-08-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_order_product_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_to_order',
            name='date_ordered',
            field=models.DateTimeField(null=True),
        ),
    ]
