# Generated by Django 2.2.4 on 2019-08-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_auto_20190824_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_to_order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
