# Generated by Django 2.2.4 on 2019-08-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0010_auto_20190824_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_to_order',
            name='date_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_to_order',
            name='toppings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
